### ISSUE TITLE
Implement CIA Labs and Other Locations

### ISSUE THREAD

**Issue by Theawesomeboophis** [Theawesomeboophis/Whaleys-Weird-World-Recreation#1]
These are buildings present in the original Reddit comments, not sure how to create crash site yet.

**Comment by Theawesomeboophis** [comment]
My plans for CIA buildings are to have a multiple level building with a basement and rooms containing cryptids, with a outside area encased with a fence and protected by CIA agent, not sure how to do this yet.

**Comment by Kenan2000** [comment]
@Theawesomeboophis Hello there, Napple on discord sent me his copy of Whaleys Weird World, apparently, it's one of the original versions apparently, it is quite old, needs to be converted to work with latest experimental version 
[Whaleys_Weird_World.zip](https://github.com/Theawesomeboophis/Whaleys-Weird-World-Recreation/files/7039615/Whaleys_Weird_World.zip), here as well

**Comment by Theawesomeboophis** [comment]
That is fantastic, tell napple thanks when you get the chance, I will look over it over the weekend.
